catalogs:
  build:
    cpx2: ^8.0.0
    tsup: ^8.5.1
    typescript: ^5.9.3
  ci:
    '@commitlint/cli': ^20.4.2
    '@commitlint/config-conventional': ^20.4.2
    '@favware/cliff-jumper': ^6.0.0
    '@nanoforge-dev/actions': ^1.1.0
    husky: ^9.1.7
    lint-staged: ^16.2.7
  core:
    '@types/node': ^25.3.2
  lint:
    '@nanoforge-dev/utils-eslint-config': ^1.0.2
    '@nanoforge-dev/utils-prettier-config': ^1.0.2
    '@trivago/prettier-plugin-sort-imports': ^6.0.2
    eslint: ^10.0.2
    prettier: ^3.8.1
  schematics:
    '@angular-devkit/core': ^21.2.0
    '@angular-devkit/schematics': ^21.2.0
    rxjs: ^7.8.2
  tests:
    '@vitest/coverage-v8': ^4.0.18
    vitest: ^4.0.18

onlyBuiltDependencies:
  - esbuild
