catalogs:
  build:
    cpx2: ^8.0.2
    tsdown: ^0.21.9
    typescript: ^6.0.3
  ci:
    '@commitlint/cli': ^20.5.0
    '@commitlint/config-conventional': ^20.5.0
    '@favware/cliff-jumper': ^6.1.0
    '@nanoforge-dev/actions': ^1.4.1
    husky: ^9.1.7
    lint-staged: ^16.4.0
  core:
    '@types/node': ^25.6.0
  lint:
    '@nanoforge-dev/utils-eslint-config': ^1.0.2
    '@nanoforge-dev/utils-prettier-config': ^1.0.2
    '@trivago/prettier-plugin-sort-imports': ^6.0.2
    eslint: ^10.2.1
    prettier: ^3.8.3
  schematics:
    '@angular-devkit/core': ^21.2.7
    '@angular-devkit/schematics': ^21.2.7
    rxjs: ^7.8.2
  tests:
    '@angular-devkit/schematics-cli': ^21.2.7
    '@vitest/coverage-v8': ^4.1.5
    vitest: ^4.1.5

onlyBuiltDependencies:
  - esbuild
