name: Synchronize Docs

on:
  push:
    branches:
      - main
    paths:
      - "docs/**"
  workflow_dispatch:

jobs:
  synchronize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout schematics
        uses: actions/checkout@v6
        with:
          path: schematics

      - name: pnpm-install
        uses: ./schematics/.github/actions/pnpm-install
        with:
          path: schematics

      - name: synchronize docs
        uses: ./schematics/node_modules/@nanoforge-dev/actions/src/synchronize-docs
        with:
          source-docs: schematics/docs/docs
          destination-docs: docs/schematics
          source-guides: schematics/docs/guides
          destination-guides: guides/schematics
          repository: nanoforge-dev/docs
          config: schematics/docs/config.json
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update schematics documentation"
