name: Synchronize Docs

on:
  push:
    branches:
      - main
    paths:
      - "docs/**"
  workflow_dispatch:

env:
  SOURCE_PATH: schematics

jobs:
  synchronize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout schematics
        uses: actions/checkout@v6
        with:
          path: ${{ env.SOURCE_PATH }}

      - name: pnpm-install
        uses: ./schematics/.github/actions/pnpm-install
        with:
          path: ${{ env.SOURCE_PATH }}
      - name: synchronize docs
        uses: ./schematics/node_modules/@nanoforge-dev/actions/src/synchronize-docs
        with:
          source-docs: ${{ env.SOURCE_PATH }}/docs/docs
          destination-docs: docs/schematics
          source-guides: ${{ env.SOURCE_PATH }}/docs/guides
          destination-guides: guides/schematics
          repository: nanoforge-dev/docs
          config: ${{ env.SOURCE_PATH }}/docs/config.json
          token: ${{ secrets.ACTIONS_KEY }}
          commit-message: "Update schematics documentation"
