name: Release

on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: Perform a dry run?
        type: boolean
        default: false

permissions:
  contents: write

jobs:
  npm-publish:
    name: npm publish
    runs-on: ubuntu-latest
    if: github.repository_owner == 'NanoForge-dev'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Prepare
        uses: ./.github/actions/prepare

      - name: Release packages
        uses: ./node_modules/@nanoforge-dev/actions/dist/release-packages
        with:
          package: "@nanoforge-dev/schematics"
          dry: ${{ inputs.dry_run }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
