name: Release

on:
  pull_request:
    types:
      - closed
    branches:
      - main

permissions:
  contents: write
  id-token: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    if: github.repository_owner == 'NanoForge-dev' && github.event.pull_request.merged == true && startsWith(github.head_ref, 'releases/')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Prepare
        uses: ./.github/actions/prepare

      - name: Release packages
        uses: ./node_modules/@nanoforge-dev/actions/actions/release-packages
        with:
          packages: "@nanoforge-dev/cli"
          tag-format: "{version}"
          latest: true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  beta-release:
    name: Beta release
    runs-on: ubuntu-latest
    if: github.repository_owner == 'NanoForge-dev' && github.event.pull_request.merged == true && !startsWith(github.head_ref, 'releases/')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Prepare
        uses: ./.github/actions/prepare

      - name: Release beta
        uses: ./node_modules/@nanoforge-dev/actions/actions/release-dev
        with:
          package: "@nanoforge-dev/schematics"
          tag: beta
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-docs:
    name: Publish docs
    runs-on: ubuntu-latest
    if: github.repository_owner == 'NanoForge-dev'
    needs: [release]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Checkout docs repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          fetch-tags: true
          path: docs-dist
          repository: nanoforge-dev/docs
          token: ${{ secrets.ACTIONS_KEY }}

      - name: Prepare
        uses: ./.github/actions/prepare

      - name: Publish docs
        uses: ./node_modules/@nanoforge-dev/actions/actions/synchronize-docs
        with:
          repository: schematics
          category: cli
